spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
websiteUrl: http://Store-api-env.eba-reeqpzfi.us-east-1.elasticbeanstalk.com
server:
  address: 0.0.0.0
  port: ${PORT:5000}
  forward-headers-strategy: framework